/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class soot_dotnet_AssemblyFile */

#ifndef _Included_soot_dotnet_AssemblyFile
#define _Included_soot_dotnet_AssemblyFile
#ifdef __cplusplus
extern "C" {
#endif
#undef soot_dotnet_AssemblyFile_serialVersionUID
#define soot_dotnet_AssemblyFile_serialVersionUID 301077366599181567LL
/*
 * Class:     soot_dotnet_AssemblyFile
 * Method:    nativeGetAllTypesMsg
 * Signature: (Ljava/lang/String;[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_soot_dotnet_AssemblyFile_nativeGetAllTypesMsg
  (JNIEnv *, jobject, jstring, jbyteArray);

/*
 * Class:     soot_dotnet_AssemblyFile
 * Method:    nativeGetMethodBodyMsg
 * Signature: (Ljava/lang/String;[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_soot_dotnet_AssemblyFile_nativeGetMethodBodyMsg
  (JNIEnv *, jobject, jstring, jbyteArray);

/*
 * Class:     soot_dotnet_AssemblyFile
 * Method:    nativeGetMethodBodyOfPropertyMsg
 * Signature: (Ljava/lang/String;[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_soot_dotnet_AssemblyFile_nativeGetMethodBodyOfPropertyMsg
  (JNIEnv *, jobject, jstring, jbyteArray);

/*
 * Class:     soot_dotnet_AssemblyFile
 * Method:    nativeGetMethodBodyOfEventMsg
 * Signature: (Ljava/lang/String;[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_soot_dotnet_AssemblyFile_nativeGetMethodBodyOfEventMsg
  (JNIEnv *, jobject, jstring, jbyteArray);

/*
 * Class:     soot_dotnet_AssemblyFile
 * Method:    nativeGetAssemblyContentMsg
 * Signature: (Ljava/lang/String;[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_soot_dotnet_AssemblyFile_nativeGetAssemblyContentMsg
  (JNIEnv *, jobject, jstring, jbyteArray);

/*
 * Class:     soot_dotnet_AssemblyFile
 * Method:    nativeIsAssembly
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_soot_dotnet_AssemblyFile_nativeIsAssembly
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
